// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Capture executed [`ExecutionPlan`] snapshots so the Java side can read
//! per-operator metrics after `collect` / `executeStream` returns.
//!
//! Side-table keyed by a stable monotonic id the Java side assigns at
//! `DataFrame` construction time. The id is *not* the JNI handle pointer,
//! because that pointer is the address of a `Box<DataFrame>` the executor
//! frees during `collect` / `executeStream`. Reusing the freed address as
//! a key would race with subsequent `ctx.sql(...)` calls -- the allocator
//! is free to hand the same address to a fresh DataFrame, and the registry
//! would silently cross-contaminate.
//!
//! The matching entry is inserted by the executor (see
//! `lib.rs::collectDataFrame` / `executeStreamDataFrame`) and removed by
//! `closeDataFrame`. The pattern is otherwise the same as `memory.rs`'s
//! `TrackingMemoryPool` registry.
//!
//! The wire format is `ExecutedPlanNodeProto` (see
//! `proto/executed_plan.proto`); proto over a hand-rolled flat buffer
//! matches the convention used by every other cross-FFI carrier in this
//! crate (`SessionOptions`, `CacheManagerOptionsProto`, etc.).

use std::collections::HashMap;
use std::sync::{Arc, Mutex, OnceLock};

use datafusion::physical_plan::display::DisplayableExecutionPlan;
use datafusion::physical_plan::metrics::{MetricValue, MetricsSet};
use datafusion::physical_plan::ExecutionPlan;
use jni::sys::jlong;
use prost::Message;

use crate::errors::JniResult;
use crate::proto_gen::ExecutedPlanNodeProto;

fn registry() -> &'static Mutex<HashMap<jlong, Arc<dyn ExecutionPlan>>> {
    static REGISTRY: OnceLock<Mutex<HashMap<jlong, Arc<dyn ExecutionPlan>>>> = OnceLock::new();
    REGISTRY.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Stash the plan against the DataFrame's stable plan id. Called from the
/// executor after `df.create_physical_plan().await` succeeds. The id is a
/// monotonic integer the Java side assigns at DataFrame construction --
/// distinct from the `Box<DataFrame>` handle, which the executor frees
/// during this same call.
pub(crate) fn register(plan_id: jlong, plan: Arc<dyn ExecutionPlan>) {
    registry()
        .lock()
        .expect("executed-plan registry lock poisoned")
        .insert(plan_id, plan);
}

/// Retrieve the planted plan for `plan_id`, if any. Returns `None` for
/// pre-execution callers; the JNI handler turns that into a clear "call
/// collect() first" message.
pub(crate) fn lookup(plan_id: jlong) -> Option<Arc<dyn ExecutionPlan>> {
    registry()
        .lock()
        .expect("executed-plan registry lock poisoned")
        .get(&plan_id)
        .cloned()
}

/// Drop the registry entry. Called from `closeDataFrame`.
pub(crate) fn unregister(plan_id: jlong) {
    registry()
        .lock()
        .expect("executed-plan registry lock poisoned")
        .remove(&plan_id);
}

/// Walk `plan` recursively and serialise as `ExecutedPlanNodeProto`-encoded
/// bytes. The Java side decodes via the autogenerated proto class.
pub(crate) fn serialise(plan: &Arc<dyn ExecutionPlan>) -> JniResult<Vec<u8>> {
    let proto = walk(plan);
    Ok(proto.encode_to_vec())
}

fn walk(plan: &Arc<dyn ExecutionPlan>) -> ExecutedPlanNodeProto {
    let display = format!(
        "{}",
        DisplayableExecutionPlan::new(plan.as_ref()).one_line()
    );
    let mut node = ExecutedPlanNodeProto {
        name: plan.name().to_string(),
        display_details: display.trim_end().to_string(),
        ..Default::default()
    };

    if let Some(metrics) = plan.metrics() {
        // Sum across partitions for the well-known variants. Same aggregation
        // upstream's MetricsSet helpers do.
        let aggregated = metrics.aggregate_by_name();

        node.output_rows = aggregated.output_rows().map(|v| v as u64);
        node.elapsed_compute_nanos = aggregated.elapsed_compute().map(|v| v as u64);
        node.output_bytes = aggregated
            .sum(|m| matches!(m.value(), MetricValue::OutputBytes(_)))
            .map(|v| v.as_usize() as u64);
        node.output_batches = aggregated
            .sum(|m| matches!(m.value(), MetricValue::OutputBatches(_)))
            .map(|v| v.as_usize() as u64);
        node.spill_count = aggregated.spill_count().map(|v| v as u64);
        node.spilled_bytes = aggregated.spilled_bytes().map(|v| v as u64);
        node.spilled_rows = aggregated.spilled_rows().map(|v| v as u64);
        node.current_memory_usage = aggregated
            .sum(|m| matches!(m.value(), MetricValue::CurrentMemoryUsage(_)))
            .map(|v| v.as_usize() as u64);

        node.custom_counters = collect_customs(&aggregated);
    }

    for child in plan.children() {
        node.children.push(walk(child));
    }
    node
}

fn collect_customs(metrics: &MetricsSet) -> HashMap<String, i64> {
    let mut map: HashMap<String, i64> = HashMap::new();
    for metric in metrics.iter() {
        if let MetricValue::Count { name, count } = metric.value() {
            *map.entry(name.to_string()).or_insert(0) += count.value() as i64;
        }
    }
    map
}
